# Generated by Django 4.2 on 2023-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_buscompany_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/company/'),
        ),
    ]
