# Generated by Django 4.1.7 on 2023-04-26 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='note',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
