# Generated by Django 4.1.7 on 2023-05-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(max_length=49),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='tours.bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='tours.route'),
        ),
    ]
